### ISSUE TITLE
How to monitor the battery status

### ISSUE THREAD

**Issue by hajo62** [dolezsa/Xiaomi_Hygrothermo#5]
I did the setup as described. Temperatur and humidity are shown as sensors, but not the battery level. I see, its _included_ in the other sensors, but as single value.
With `monitored_conditions` it results in an error.
Also tried with value_template (to add a constant to the humidity), also without success.
```
  - platform: xiaomi_hygrothermo
    name: mijia ht #1
    mac: '44:66:AA:DD:FF:DD'
    scan_interval: 60
    monitored_conditions:
      - temperature
      - humidity
#      - battery
```
<img width="217" alt="image" src="https://user-images.githubusercontent.com/15800980/56081428-94782b80-5e0d-11e9-83b2-c26a2658f5bd.png">

**Comment by dolezsa** [comment]
monitored_conditions key is not supported by my component, you should delete it (and also lines after that)... you can find battery status if you click to sensor...:
![image](https://user-images.githubusercontent.com/37278442/56393084-92f69b00-6233-11e9-9b7b-baf26abd57db.png)

**Comment by hajo62** [comment]
Thanks for clarifying the monitored conditions.

Would it be possible to enhance your software to expose the battery level as an own value? Than it would be possible to set an alarm or to watch that together with all other batteries at a single place.

Thanks for your integration. Works very well!!!

**Comment by dolezsa** [comment]
you can expose battery level using template sensor like this:

```
sensor:
  - platform: template
    sensors:
      mijia_ht_battery:
        friendly_name: "mijia ht battery level"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.mijia_ht_temperature', 'battery_level') }}"
```

**Comment by hajo62** [comment]
Might you help one more time, please?
I would like to correct the humidity value by substracting 3%.
When I try to adapt you code from above, I get a none numeric value.
`value_template: "{{ state_attr('sensor.mijia_ht_humidity', 'humidity') - 3 }}"`

**Comment by dolezsa** [comment]
you should try this:
'''
{{ states('sensor.mijia_ht_humidity')|float - 3 }}
'''

**Comment by hajo62** [comment]
Thanks. Did it as shown below. The corrected value results in a second sensor. That's what you meant?
```
  - platform: xiaomi_hygrothermo
    name: Hygrothermo_1
    mac: '44:66:AA:DD:FF:DD'
    scan_interval: 60

  # Batterie-Level als Extra-Wert
  - platform: template
    sensors:
      hygrothermo_1_battery:
        friendly_name: "Hygrothermo 1 Battery Level"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('sensor.hygrothermo_1_temperature', 'battery_level') }}"

  - platform: template
    sensors:
      corr_hygrothermo_1_humidity:
        friendly_name: "corr. Hygrothermo 1 Humidity"
        unit_of_measurement: '%'
        value_template: "{{ states('sensor.hygrothermo_1_humidity')|float - 3 }}"
```
